# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/rawnly/gh-targetprocess

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -tags=nodbus
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w
      - -X github.com/rawnly/gh-targetprocess/cmd.Version={{.Version}}
      - -X github.com/rawnly/gh-targetprocess/cmd.Commit={{.Commit}}
      - -X github.com/rawnly/gh-targetprocess/cmd.Date={{.CommitDate}}
      - -X github.com/rawnly/gh-targetprocess/internal/telemetry.PostHogAPIKey={{.Env.POSTHOG_API_KEY}}

archives:
  - formats:
      - binary
    name_template: "gh_targetprocess_{{ .Tag }}_{{ .Os }}-{{ .Arch }}{{if .Arm}}_{{.Arm}}{{end}}"

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  header: |
    # {{ .Version }}

    To update run 
    ```bash
    gh extension upgrade targetprocess
    ```
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*\\(deps\\)*:+.*$"
      order: 300
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999
