[tools]
go = "1.25"
cobra-cli = "latest"

[tool_alias]
cobra-cli = "go:github.com/spf13/cobra-cli"

[tasks.build]
run = 'goreleaser build --snapshot --clean'

[env]
_.file = { path = '.env', redact = true }
